//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbl_demoEntities : DbContext
    {
        public dbl_demoEntities()
            : base("name=dbl_demoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book_Inventory_Table> Book_Inventory_Table { get; set; }
        public DbSet<Book_Request_Table1> Book_Request_Table1 { get; set; }
        public DbSet<Login_Table> Login_Table { get; set; }
        public DbSet<Student_Table> Student_Table { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
